version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./local_db.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgresdb
      PYTHONUNBUFFERED: "1"
    command: >
      sh -c "
        echo 'Ждём старта БД…' &&
        sleep 15 &&
        uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "3000:80"

volumes:
  pgdata:
